services:
  banek:
    container_name: banek
    image: fruworg/banek
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./content.json:/app/content.json
    networks:
      - banek
networks:
  banek:
    enable_ipv6: true
