services:
  banek:
    container_name: banek
    image: fruworg/banek
    ports:
      - "127.0.0.1:9999:9999"
    volumes:
      - ./config/content.json:/app/config/content.json
      - ./config/template.html:/app/config/template.html
    networks:
      - banek
networks:
  banek:
    enable_ipv6: true
